version: "3"

services:
  api:
    image: node:20.15.1
    working_dir: /usr/src/applause
    volumes:
      - ./api:/usr/src/applause
  web:
    image: node:20.15.1
    working_dir: /usr/src/applause
    volumes:
      - ./web:/usr/src/applause
  db:
    image: mongo
    restart: always