version: "3"

services:
  api:
    image: node:20.15.1
    working_dir: /usr/src/applause
    user: node
    volumes:
      - ./api:/usr/src/applause:z
  web:
    image: node:20.15.1
    working_dir: /usr/src/applause
    volumes:
      - ./web:/usr/src/applause:z
    command: yarn dev
    user: node
  db:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_pass

volumes:
  database: